# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Create fibonacci secuence
numberA = 0
numberB = 1
sum = 0

while True:
  # Asign the actual numberB to the number A, next the numberB is equal to the before numberB and the actual numberA
  numberA, numberB = numberB, numberA + numberB
  # Validate if the actual number is less to four billion
  if numberB > 4000000:
    break
  #Validate if the actual number is par, and add to the total sum
  if numberB % 2 == 0:
    sum += numberB

print(sum)